version: "3.7"
services:
  app:
    container_name: dockerized-ranek
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
  json-server:
    container_name: dockerized-json-server
    build:
      context: .
      dockerfile: Dockerfile
    image: codfish/json-server
    command: npm run server
    ports:
      - "8080:4000"
    volumes:
      - ./db.js:/app/db.js:delegated
    environment:
      - NODE_ENV=development
